---
abstract: 'Documentation and tools for using Platypus with the Free Pascal programming language'
author:
  - 'Graham Ollis <plicease@cpan.org>'
build_requires:
  FFI::CheckLib: '0'
  File::Which: '0'
  Module::Build: '0.38'
  Module::Build::FFI: '0.19'
  Module::Build::FFI::Pascal: '0.49'
configure_requires:
  File::Which: '0'
  Module::Build: '0.38'
  Module::Build::FFI: '0.19'
  Module::Build::FFI::Pascal: '0.49'
dynamic_config: 1
generated_by: 'Module::Build version 0.4224, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: FFI-Platypus-Lang-Pascal
no_index:
  directory:
    - examples
provides:
  FFI::Platypus::Lang::Pascal:
    file: lib/FFI/Platypus/Lang/Pascal.pm
    version: '0.05'
requires:
  FFI::ExtractSymbols: '0'
  FFI::Platypus: '0.19'
  perl: '5.008001'
resources:
  IRC: irc://irc.perl.org/#native
  bugtracker: http://github.com/Perl5-FFI/FFI-Platypus-Lang-Pascal/issues
  license: http://dev.perl.org/licenses/
  repository: http://github.com/Perl5-FFI/FFI-Platypus-Lang-Pascal
version: '0.05'
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
